name: swissborg-get-yields-daily
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: POST /api/swissborg/cron/yield
        run: |
          curl --fail --verbose -L -X POST                                        \
               --url https://crypto-tools.andstuff.dev/api/swissborg/cron/yield  \
               --header "Authorization: Bearer ${{ secrets.CRON_KEY }}"
