name: swissborg-get-yields-daily
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cron-swissborg-yield.yaml'
  schedule:
    - cron: '0 21 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: POST /api/swissborg/cron/yield
        run: |
          curl --fail --verbose -X POST                                        \
               --url https://crypto-tools.vercel.app/api/swissborg/cron/yield  \
               --header "Authorization: Bearer ${{ secrets.CRON_KEY }}"
