name: swissborg-compute-yield-averages-daily
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: POST /api/swissborg/cron/yield-average
        run: |
          curl --fail --verbose -L -X POST                                                \
               --url https://crypto-tools.andstuff.dev/api/swissborg/cron/yield-average  \
               --header "Authorization: Bearer ${{ secrets.CRON_KEY }}"
